/* tslint:disable */
/* eslint-disable */
/**
 * CRM System API
 * API for managing Clients and Invoices
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClientResponse
 */
export interface ClientResponse {
    /**
     * 
     * @type {string}
     * @memberof ClientResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ClientResponse
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof ClientResponse
     */
    phone?: string;
    /**
     * 
     * @type {number}
     * @memberof ClientResponse
     */
    id?: number;
}

/**
 * Check if a given object implements the ClientResponse interface.
 */
export function instanceOfClientResponse(value: object): value is ClientResponse {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function ClientResponseFromJSON(json: any): ClientResponse {
    return ClientResponseFromJSONTyped(json, false);
}

export function ClientResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function ClientResponseToJSON(json: any): ClientResponse {
    return ClientResponseToJSONTyped(json, false);
}

export function ClientResponseToJSONTyped(value?: ClientResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
        'phone': value['phone'],
        'id': value['id'],
    };
}

